#!/usr/bin/env zsh
# Filename: $HOME/.zsh/func/prompt_heavy_setup
# Purpose:  "heavy" prompt theme for zsh
# Author:   Michael Prokop / www.michael-prokop.at / www.grml.org
# Credits:  Matthias Kopfermann
# Latest change: Mon Jun 21 01:49:24 CEST 2004
################################################################################
# How to use this file:
# - put this file in your $fpath (e.g. $ZSHDIR/func/ in my setup)
# - run "autoload promptinit && promptinit" to initialise the prompt-feature
# - see "prompt -h" for more information
# 
# Some notes:
# I noticed a quite interesting behaviour of some prompt-themes.
# Check it out on your own:
# 
# $ zsh -f                             # start up zsh without config-files
# $ echo $PROMPT                       # print out value of $PROMPT
# $ vared fpath                        # edit $fpath if necessary
# $ autoload promptinit && promptinit  # now initialise the prompt-feature
# $ prompt -p                          # print out preview of available prompts
# $ echo $PROMPT                       # print out value of $PROMPT
#
# See what I mean?
#
# TODO
# add option-handling for setting colors
#
# History:
# 040620 initial version
################################################################################

netbeat() {
   zmodload -i zsh/datetime
   let float_netbeat="( (  (`strftime "%s" $EPOCHSECONDS` + 3600) % 86400)/86.4)"
   typeset -i int_netbeat=$float_netbeat
   print @$int_netbeat
}

setpromptheavy () {
  unset PS1 PS2 PS3 PS4 PROMPT RPROMPT # try to fix strange behaviour
                                       # (see header of this file)
## define colors if not set by user
#  local brackets=${1:-'red'}
#  local background=${2:-'black'}
#  local at=${3:-'red'}
#  local user=${4:-'yellow'}
#  local history=${5:-'blue'}
#  local cwd=${6:-'yellow'}
#  local exit=${6:-'red'}
#
## define colors
#  local C_AT="%{$reset_color$fg[$at]$bg[$background]%}"
#  local C_BRACKETS="%{$bold_color$fg[$brackets]$bg[$background]%}"
#  local C_CWD="%{$bold_color$fg[$cwd]$bg[$background]%}"
#  local C_HISTORY="%{$bold_color$fg[$history]$bg[$background]%}"
#  local C_RESET="%{$reset_color%}"
#  local C_USER="%{$reset_color$fg[$user]$bg[$background]%}"
#  local C_EXIT="%{$bold_color$fg[$exit]$bg[$background]%}"
#  local BRACKET_L='['
#  local BRACKET_R=']'
#  local EXITCODE="%(?..%?%1v )"

  local NINE_LI='_________'
  local off=$(builtin echo "%{[0m%}")
  local bright=$(builtin echo "%{[01m%}") 
  local onred=$(builtin echo "%{[1m[41m%}")
  local ongreen=$(builtin echo "%{[42m%}")
  local green=$(builtin echo "%{[32m%}")
  local onyellow=$(builtin echo "%{[1m[43m%}")
  local yellow=$(builtin echo "%{[33m%}")
  local blue=$(builtin echo "%{[34m%}")
  local onblue=$(builtin echo "%{[44m%}")
          farbe=${blue}
          farbe=${red}
          farbe=${magenta}
  local LINE="$blue$NINE_LI$off$NINE_LI"
        GERDATE=%D{%d.%m.%y}
  local PATHSHOW=%~
  local HISTNR=%h


  case $TERM in
    xterm*)
        local TITLEBAR='%{]0;%n@%m:%~%}'
        ;;
    *)
        local TITLEBAR=""
        ;;
  esac

# now set prompt
  if [[ "$TERM" != "dumb" ]]; then
    PROMPT="$LINE$LINE$blue$LINE$LINE
[$bright$green$PATHSHOW$off] \
$bright$farbe$off${farbe}\
TTY:$green%l${off}__${farbe}hist:$HISTNR${off}__${farbe}\
$GERDATE $off$bright$onred %? 
${bright}${yellow}%v${off}${red}%#%B $off" 
  else
    PROMPT="%(?..[%?] )%n@%m:%~> "
  fi
}

# pre-execute - useful for setting title of screen windows
preexec () {
    if [[ "$STY" != "" ]]; then
        #local CMD=`echo $1 | sed 's/^sudo //; s/ .*//'`
        echo -n "k$1\\"
    fi
}

# print information when user runs 'prompt -h heavy'
#prompt_heavy_help () {
#  cat <<EOH
#This prompt is color-scheme-able.  You can invoke it thus:
#
#  prompt heavy [<brackets> [<background> [<at> [<user> [<history> [<cwd>]]]]]]
#
#  defaults are \`red black red yellow blue yellow red'
#EOH
#}

prompt_heavy_setup () {
  precmd () {
    setopt promptsubst
    if jobs % >& /dev/null; then
      psvar=("*")
    else
      psvar=`netbeat`
    fi
    setpromptheavy
  }
# preexec () { }
}

#prompt_heavy_preview () {
#  if (( ! $#* )); then
#    prompt_preview_theme heavy
#    print
#    prompt_preview_theme heavy red blue red yellow blue yellow red
#  else
#    prompt_preview_theme heavy "$@"
#  fi
#}

prompt_heavy_setup "$@"
######## END OF FILE ###########################################################
